services:
  - type: web
    name: django-audio-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_NAME
        value: your_database_name
      - key: DB_USER
        value: your_mysql_username
      - key: DB_PASSWORD
        value: your_mysql_password
      - key: DB_HOST
        value: your.mysql.host.com
      - key: DB_PORT
        value: 3306
